export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_REQ = 'REGISTER_REQ';
export const REGISTER_SUC = 'REGISTER_SUC';
export const REGISTER_ERR = 'REGISTER_ERR';
export const LOAD_USER_REQ = 'LOAD_USER_REQ';
export const LOAD_USER_SUC = 'LOAD_USER_SUC';
export const LOAD_USER_ERR = 'LOAD_USER_ERR';
export const LOGIN_REQ = 'LOGIN_REQ';
export const LOGIN_SUC = 'LOGIN_SUC';
export const LOGIN_ERR = 'LOGIN_ERR';
export const LOGOUT = 'LOGOUT';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const NEW_PROJECT_REQUEST = 'NEW_PROJECT_REQUEST';
export const NEW_PROJECT_SUCCESS = 'NEW_PROJECT_SUCCESS';
export const NEW_PROJECT_ERROR = 'NEW_PROJECT_ERROR';
export const SELECT_PROJECT_REQUEST = 'SELECT_PROJECT_REQUEST';
export const SELECT_PROJECT_SUCCESS = 'SELECT_PROJECT_SUCCESS';
export const SELECT_PROJECT_ERROR = 'SELECT_PROJECT_ERROR';
export const DESELECT_PROJECT = 'DESELECT_PROJECT';

export const GET_SPRINTS_REQUEST = 'GET_SPRINTS_REQUEST';
export const GET_SPRINTS_SUCCESS = 'GET_SPRINTS_SUCCESS';
export const GET_SPRINTS_ERROR = 'GET_SPRINTS_ERROR';

export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_REQUEST = 'GET_TICKETS_REQUEST';
export const GET_TICKETS_ERROR = 'GET_TICKETS_ERROR';
export const GET_TICKET_SUC = 'GET_TICKET_SUC';
export const GET_TICKET_REQ = 'GET_TICKET_REQ';
export const GET_TICKET_ERR = 'GET_TICKET_ERR';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const UPDATE_USER_REQUEST = 'UPDATE_USERS_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USERS_ERROR';
